services:
  - type: web
    name: apppot
    previews:
      generation: automatic
    env: node
    buildCommand: npm run install:all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
